# AiOne MoniHub Java Agent 配置示例
monihub:
  agent:
    # 实例ID（必填，需要先在服务端创建实例）
    application-code: ${AGENT_APPLICATION_CODE:3ASDFASDF}
    # 服务端URL
    server-url: ${AGENT_SERVER_URL:http://localhost:9080}
    # Debug模式，开启后会打印详细日志，默认关闭
    debug: ${AGENT_DEBUG:false}
# Spring Boot 配置
spring:
  application:
    name: aione-monihub-agent

# 日志配置
logging:
  level:
    root: INFO

server:
  port: 8080
